export type FormationPosition = {
  id: number;
  group: 'GK' | 'DF' | 'MF' | 'FW';
  position:
    | 'GK'
    | 'CB'
    | 'LB'
    | 'RB'
    | 'LWB'
    | 'RWB'
    | 'DM'
    | 'CM'
    | 'AM'
    | 'LM'
    | 'RM'
    | 'LW'
    | 'RW'
    | 'ST'
    | 'SS';
  top: number;
  left: number;
};

export const FORMATION_LIST = [
  '2-3-4-1',
  '3-5-2',
  '3-4-3',
  '3-4-2-1',
  '3-4-1-2',
  '3-1-4-2',
  '3-5-1-1',
  '3-3-4',
  '3-3-1-3',
  '3-3-3-1',
  '3-2-4-1',
  '4-2-3-1',
  '4-3-3',
  '4-4-2',
  '4-1-4-1',
  '4-3-1-2',
  '4-4-1-1',
  '4-5-1',
  '4-2-2-2',
  '4-3-2-1',
  '4-1-3-2',
  '4-1-2-3',
  '4-2-4',
  '4-2-1-3',
  '5-3-2',
  '5-4-1',
  '5-2-3',
  '5-2-2-1',
] as const;

export type FormationType = (typeof FORMATION_LIST)[number];

export const FORMATION_POSITIONS: Record<FormationType, FormationPosition[]> = {
  '2-3-4-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 4, group: 'MF', position: 'CM', top: 50, left: 25 },
    { id: 5, group: 'MF', position: 'DM', top: 50, left: 50 },
    { id: 6, group: 'MF', position: 'CM', top: 50, left: 75 },
    { id: 7, group: 'MF', position: 'LM', top: 27, left: 13 },
    { id: 8, group: 'MF', position: 'AM', top: 30, left: 35 },
    { id: 9, group: 'MF', position: 'AM', top: 30, left: 65 },
    { id: 10, group: 'MF', position: 'RM', top: 27, left: 87 },
    { id: 11, group: 'FW', position: 'ST', top: 10, left: 50 },
  ],
  '3-5-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'DF', position: 'LWB', top: 38, left: 10 },
    { id: 6, group: 'MF', position: 'CM', top: 43, left: 30 },
    { id: 7, group: 'MF', position: 'DM', top: 50, left: 50 },
    { id: 8, group: 'MF', position: 'CM', top: 43, left: 70 },
    { id: 9, group: 'DF', position: 'RWB', top: 38, left: 90 },
    { id: 10, group: 'FW', position: 'SS', top: 15, left: 35 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 65 },
  ],
  '3-4-2-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'DF', position: 'LWB', top: 45, left: 15 },
    { id: 6, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 7, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 8, group: 'DF', position: 'RWB', top: 45, left: 85 },
    { id: 9, group: 'MF', position: 'AM', top: 25, left: 35 },
    { id: 10, group: 'MF', position: 'AM', top: 25, left: 65 },
    { id: 11, group: 'FW', position: 'ST', top: 10, left: 50 },
  ],
  '3-4-1-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'DF', position: 'LWB', top: 45, left: 15 },
    { id: 6, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 7, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 8, group: 'DF', position: 'RWB', top: 45, left: 85 },
    { id: 9, group: 'MF', position: 'AM', top: 30, left: 50 },
    { id: 10, group: 'FW', position: 'SS', top: 15, left: 35 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 65 },
  ],
  '3-1-4-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'MF', position: 'DM', top: 50, left: 50 },
    { id: 6, group: 'MF', position: 'LM', top: 40, left: 12 },
    { id: 7, group: 'MF', position: 'CM', top: 43, left: 33 },
    { id: 8, group: 'MF', position: 'CM', top: 43, left: 67 },
    { id: 9, group: 'MF', position: 'RM', top: 40, left: 88 },
    { id: 10, group: 'FW', position: 'SS', top: 15, left: 38 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 62 },
  ],
  '3-5-1-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'DF', position: 'LWB', top: 40, left: 12 },
    { id: 6, group: 'MF', position: 'CM', top: 47, left: 30 },
    { id: 7, group: 'MF', position: 'DM', top: 50, left: 50 },
    { id: 8, group: 'MF', position: 'CM', top: 47, left: 70 },
    { id: 9, group: 'DF', position: 'RWB', top: 40, left: 88 },
    { id: 10, group: 'MF', position: 'AM', top: 30, left: 50 },
    { id: 11, group: 'FW', position: 'ST', top: 10, left: 50 },
  ],
  '3-3-4': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'MF', position: 'DM', top: 45, left: 25 },
    { id: 6, group: 'MF', position: 'CM', top: 50, left: 50 },
    { id: 7, group: 'MF', position: 'CM', top: 45, left: 75 },
    { id: 8, group: 'FW', position: 'LW', top: 20, left: 13 },
    { id: 9, group: 'FW', position: 'ST', top: 23, left: 35 },
    { id: 10, group: 'FW', position: 'ST', top: 23, left: 65 },
    { id: 11, group: 'FW', position: 'RW', top: 20, left: 87 },
  ],
  '3-3-1-3': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'MF', position: 'DM', top: 43, left: 27 },
    { id: 6, group: 'MF', position: 'CM', top: 50, left: 50 },
    { id: 7, group: 'MF', position: 'CM', top: 43, left: 73 },
    { id: 8, group: 'MF', position: 'AM', top: 33, left: 50 },
    { id: 9, group: 'FW', position: 'LW', top: 20, left: 23 },
    { id: 10, group: 'FW', position: 'ST', top: 15, left: 50 },
    { id: 11, group: 'FW', position: 'RW', top: 20, left: 77 },
  ],
  '3-3-3-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'MF', position: 'DM', top: 43, left: 27 },
    { id: 6, group: 'MF', position: 'CM', top: 50, left: 50 },
    { id: 7, group: 'MF', position: 'CM', top: 43, left: 73 },
    { id: 8, group: 'MF', position: 'LM', top: 25, left: 20 },
    { id: 9, group: 'MF', position: 'AM', top: 25, left: 50 },
    { id: 10, group: 'MF', position: 'RM', top: 25, left: 80 },
    { id: 11, group: 'FW', position: 'ST', top: 10, left: 50 },
  ],
  '3-4-3': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'DF', position: 'LWB', top: 43, left: 12 },
    { id: 6, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 7, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 8, group: 'DF', position: 'RWB', top: 43, left: 88 },
    { id: 9, group: 'FW', position: 'SS', top: 23, left: 25 },
    { id: 10, group: 'FW', position: 'ST', top: 15, left: 50 },
    { id: 11, group: 'FW', position: 'SS', top: 23, left: 75 },
  ],
  '4-3-3': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'CM', top: 43, left: 30 },
    { id: 7, group: 'MF', position: 'DM', top: 50, left: 50 },
    { id: 8, group: 'MF', position: 'CM', top: 43, left: 70 },
    { id: 9, group: 'FW', position: 'LW', top: 20, left: 20 },
    { id: 10, group: 'FW', position: 'ST', top: 15, left: 50 },
    { id: 11, group: 'FW', position: 'RW', top: 20, left: 80 },
  ],
  '4-2-3-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 7, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 8, group: 'MF', position: 'LM', top: 30, left: 15 },
    { id: 9, group: 'MF', position: 'AM', top: 30, left: 50 },
    { id: 10, group: 'MF', position: 'RM', top: 30, left: 85 },
    { id: 11, group: 'FW', position: 'ST', top: 10, left: 50 },
  ],
  '3-2-4-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'CB', top: 70, left: 25 },
    { id: 3, group: 'DF', position: 'CB', top: 70, left: 50 },
    { id: 4, group: 'DF', position: 'CB', top: 70, left: 75 },
    { id: 5, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 6, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 7, group: 'MF', position: 'LM', top: 28, left: 12 },
    { id: 8, group: 'MF', position: 'AM', top: 32, left: 35 },
    { id: 9, group: 'MF', position: 'AM', top: 32, left: 65 },
    { id: 10, group: 'MF', position: 'RM', top: 28, left: 88 },
    { id: 11, group: 'FW', position: 'ST', top: 12, left: 50 },
  ],
  '4-4-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'LM', top: 33, left: 12 },
    { id: 7, group: 'MF', position: 'DM', top: 48, left: 35 },
    { id: 8, group: 'MF', position: 'CM', top: 48, left: 65 },
    { id: 9, group: 'MF', position: 'RM', top: 33, left: 88 },
    { id: 10, group: 'FW', position: 'SS', top: 15, left: 35 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 65 },
  ],
  '4-1-4-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'DM', top: 55, left: 50 },
    { id: 7, group: 'MF', position: 'LM', top: 35, left: 12 },
    { id: 8, group: 'MF', position: 'CM', top: 40, left: 33 },
    { id: 9, group: 'MF', position: 'CM', top: 40, left: 67 },
    { id: 10, group: 'MF', position: 'RM', top: 35, left: 88 },
    { id: 11, group: 'FW', position: 'ST', top: 20, left: 50 },
  ],
  '4-3-1-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'CM', top: 45, left: 30 },
    { id: 7, group: 'MF', position: 'DM', top: 50, left: 50 },
    { id: 8, group: 'MF', position: 'CM', top: 45, left: 70 },
    { id: 9, group: 'MF', position: 'AM', top: 30, left: 50 },
    { id: 10, group: 'FW', position: 'SS', top: 15, left: 35 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 65 },
  ],
  '4-4-1-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'LM', top: 43, left: 15 },
    { id: 7, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 8, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 9, group: 'MF', position: 'RM', top: 43, left: 85 },
    { id: 10, group: 'MF', position: 'AM', top: 30, left: 50 },
    { id: 11, group: 'FW', position: 'ST', top: 10, left: 50 },
  ],
  '4-5-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'LM', top: 40, left: 12 },
    { id: 7, group: 'MF', position: 'DM', top: 45, left: 32 },
    { id: 8, group: 'MF', position: 'CM', top: 52, left: 50 },
    { id: 9, group: 'MF', position: 'CM', top: 45, left: 68 },
    { id: 10, group: 'MF', position: 'RM', top: 40, left: 88 },
    { id: 11, group: 'FW', position: 'ST', top: 20, left: 50 },
  ],
  '4-2-2-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'AM', top: 33, left: 12 },
    { id: 7, group: 'MF', position: 'DM', top: 48, left: 35 },
    { id: 8, group: 'MF', position: 'CM', top: 48, left: 65 },
    { id: 9, group: 'MF', position: 'AM', top: 33, left: 88 },
    { id: 10, group: 'FW', position: 'SS', top: 15, left: 35 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 65 },
  ],
  '4-3-2-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'CM', top: 48, left: 30 },
    { id: 7, group: 'MF', position: 'DM', top: 55, left: 50 },
    { id: 8, group: 'MF', position: 'CM', top: 48, left: 70 },
    { id: 9, group: 'MF', position: 'AM', top: 28, left: 35 },
    { id: 10, group: 'MF', position: 'AM', top: 28, left: 65 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 50 },
  ],
  '4-1-3-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'DM', top: 55, left: 50 },
    { id: 7, group: 'MF', position: 'LM', top: 38, left: 25 },
    { id: 8, group: 'MF', position: 'AM', top: 38, left: 50 },
    { id: 9, group: 'MF', position: 'RM', top: 38, left: 75 },
    { id: 10, group: 'FW', position: 'SS', top: 15, left: 35 },
    { id: 11, group: 'FW', position: 'ST', top: 15, left: 65 },
  ],
  '4-1-2-3': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'DM', top: 55, left: 50 },
    { id: 7, group: 'MF', position: 'CM', top: 43, left: 30 },
    { id: 8, group: 'MF', position: 'CM', top: 43, left: 70 },
    { id: 9, group: 'FW', position: 'LW', top: 25, left: 17 },
    { id: 10, group: 'FW', position: 'ST', top: 15, left: 50 },
    { id: 11, group: 'FW', position: 'RW', top: 25, left: 83 },
  ],
  '4-2-4': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 7, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 8, group: 'FW', position: 'LW', top: 20, left: 12 },
    { id: 9, group: 'FW', position: 'ST', top: 23, left: 35 },
    { id: 10, group: 'FW', position: 'ST', top: 23, left: 65 },
    { id: 11, group: 'FW', position: 'RW', top: 20, left: 88 },
  ],
  '4-2-1-3': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 73, left: 35 },
    { id: 4, group: 'DF', position: 'CB', top: 73, left: 65 },
    { id: 5, group: 'DF', position: 'RB', top: 68, left: 90 },
    { id: 6, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 7, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 8, group: 'MF', position: 'AM', top: 33, left: 50 },
    { id: 9, group: 'FW', position: 'LW', top: 18, left: 17 },
    { id: 10, group: 'FW', position: 'ST', top: 15, left: 50 },
    { id: 11, group: 'FW', position: 'RW', top: 18, left: 83 },
  ],
  '5-3-2': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LWB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 75, left: 28 },
    { id: 4, group: 'DF', position: 'CB', top: 75, left: 50 },
    { id: 5, group: 'DF', position: 'CB', top: 75, left: 72 },
    { id: 6, group: 'DF', position: 'RWB', top: 68, left: 90 },
    { id: 7, group: 'MF', position: 'CM', top: 45, left: 28 },
    { id: 8, group: 'MF', position: 'DM', top: 53, left: 50 },
    { id: 9, group: 'MF', position: 'CM', top: 45, left: 72 },
    { id: 10, group: 'FW', position: 'SS', top: 20, left: 35 },
    { id: 11, group: 'FW', position: 'ST', top: 20, left: 65 },
  ],
  '5-4-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LWB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 75, left: 28 },
    { id: 4, group: 'DF', position: 'CB', top: 75, left: 50 },
    { id: 5, group: 'DF', position: 'CB', top: 75, left: 72 },
    { id: 6, group: 'DF', position: 'RWB', top: 68, left: 90 },
    { id: 7, group: 'MF', position: 'LM', top: 45, left: 12 },
    { id: 8, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 9, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 10, group: 'MF', position: 'RM', top: 45, left: 88 },
    { id: 11, group: 'FW', position: 'ST', top: 20, left: 50 },
  ],
  '5-2-3': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LWB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 75, left: 28 },
    { id: 4, group: 'DF', position: 'CB', top: 75, left: 50 },
    { id: 5, group: 'DF', position: 'CB', top: 75, left: 72 },
    { id: 6, group: 'DF', position: 'RWB', top: 68, left: 90 },
    { id: 7, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 8, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 9, group: 'FW', position: 'SS', top: 25, left: 25 },
    { id: 10, group: 'FW', position: 'ST', top: 20, left: 50 },
    { id: 11, group: 'FW', position: 'SS', top: 25, left: 75 },
  ],
  '5-2-2-1': [
    { id: 1, group: 'GK', position: 'GK', top: 90, left: 50 },
    { id: 2, group: 'DF', position: 'LWB', top: 68, left: 10 },
    { id: 3, group: 'DF', position: 'CB', top: 75, left: 28 },
    { id: 4, group: 'DF', position: 'CB', top: 75, left: 50 },
    { id: 5, group: 'DF', position: 'CB', top: 75, left: 72 },
    { id: 6, group: 'DF', position: 'RWB', top: 68, left: 90 },
    { id: 7, group: 'MF', position: 'DM', top: 50, left: 35 },
    { id: 8, group: 'MF', position: 'CM', top: 50, left: 65 },
    { id: 9, group: 'MF', position: 'AM', top: 25, left: 35 },
    { id: 10, group: 'MF', position: 'AM', top: 25, left: 65 },
    { id: 11, group: 'FW', position: 'ST', top: 10, left: 50 },
  ],
};
