import type { TuningDataset } from '@/lib/types/syntax-integration';

export const sampleTuningDataset: TuningDataset = {
  datasetId: 'tuning_chelsea_fulham_sub65_static01',
  timestamp: new Date().toISOString(),
  matchMetadata: {
    homeTeam: 'Chelsea',
    awayTeam: 'Fulham',
    actionType: "65' Enzo Sub - 22 Player Full Matchup Setup",
  },
  aiDraft: {
    version: '1.0.0',
    tacticalScenes: [
      {
        id: 'scene-1',
        title: "Chelsea vs Fulham (65' Matchup Setup)",
        description: '65分 エンソ投入時の22名Full噛み合わせ基本配置',
        players: [
          {
            id: 'che-sanchez',
            team: 'home',
            jerseyNumber: 1,
            x: 6.0,
            y: 50.0,
            annotation: 'Sanchez',
          },
          {
            id: 'che-acheampong',
            team: 'home',
            jerseyNumber: 34,
            x: 22.0,
            y: 78.0,
            annotation: 'Acheampong',
          },
          {
            id: 'che-lacroix',
            team: 'home',
            jerseyNumber: 4,
            x: 18.0,
            y: 50.0,
            annotation: 'Lacroix',
          },
          {
            id: 'che-colwill',
            team: 'home',
            jerseyNumber: 6,
            x: 22.0,
            y: 22.0,
            annotation: 'Colwill',
          },
          {
            id: 'che-james',
            team: 'home',
            jerseyNumber: 24,
            x: 38.0,
            y: 62.0,
            annotation: 'James',
          },
          {
            id: 'che-enzo',
            team: 'home',
            jerseyNumber: 8,
            x: 36.0,
            y: 38.0,
            annotation: 'Enzo',
          },
          {
            id: 'che-gusto',
            team: 'home',
            jerseyNumber: 27,
            x: 58.0,
            y: 88.0,
            annotation: 'Gusto',
          },
          {
            id: 'che-palmer',
            team: 'home',
            jerseyNumber: 20,
            x: 56.0,
            y: 64.0,
            annotation: 'Palmer',
          },
          {
            id: 'che-rogers',
            team: 'home',
            jerseyNumber: 19,
            x: 58.0,
            y: 36.0,
            annotation: 'Rogers',
          },
          {
            id: 'che-hato',
            team: 'home',
            jerseyNumber: 33,
            x: 58.0,
            y: 12.0,
            annotation: 'Hato',
          },
          {
            id: 'che-pedro',
            team: 'home',
            jerseyNumber: 9,
            x: 72.0,
            y: 50.0,
            annotation: 'J.Pedro',
          },
          {
            id: 'ful-leno',
            team: 'away',
            jerseyNumber: 1,
            x: 94.0,
            y: 50.0,
            annotation: 'Leno',
          },
          {
            id: 'ful-castagne',
            team: 'away',
            jerseyNumber: 21,
            x: 76.0,
            y: 15.0,
            annotation: 'Castagne',
          },
          {
            id: 'ful-cuenca',
            team: 'away',
            jerseyNumber: 15,
            x: 78.0,
            y: 38.0,
            annotation: 'Cuenca',
          },
          {
            id: 'ful-bassey',
            team: 'away',
            jerseyNumber: 3,
            x: 78.0,
            y: 62.0,
            annotation: 'Bassey',
          },
          {
            id: 'ful-robinson',
            team: 'away',
            jerseyNumber: 33,
            x: 76.0,
            y: 85.0,
            annotation: 'Robinson',
          },
          {
            id: 'ful-bobb',
            team: 'away',
            jerseyNumber: 11,
            x: 52.0,
            y: 18.0,
            annotation: 'Bobb',
          },
          {
            id: 'ful-berge',
            team: 'away',
            jerseyNumber: 16,
            x: 54.0,
            y: 40.0,
            annotation: 'Berge',
          },
          {
            id: 'ful-iwobi',
            team: 'away',
            jerseyNumber: 17,
            x: 54.0,
            y: 60.0,
            annotation: 'Iwobi',
          },
          {
            id: 'ful-palacios',
            team: 'away',
            jerseyNumber: 20,
            x: 52.0,
            y: 82.0,
            annotation: 'Palacios',
          },
          {
            id: 'ful-king',
            team: 'away',
            jerseyNumber: 7,
            x: 32.0,
            y: 42.0,
            annotation: 'King',
          },
          {
            id: 'ful-garcia',
            team: 'away',
            jerseyNumber: 9,
            x: 34.0,
            y: 58.0,
            annotation: 'Garcia',
          },
        ],
        arrows: [],
        zones: [],
      },
    ],
  },
  humanGroundTruth: {
    version: '1.0.0',
    tacticalScenes: [
      {
        id: 'scene-1',
        title: "Chelsea vs Fulham (65' Matchup Setup)",
        description: '65分 エンソ投入時の22名Full噛み合わせ基本配置',
        players: [
          {
            id: 'che-sanchez',
            team: 'home',
            jerseyNumber: 1,
            x: 6.0,
            y: 50.0,
            annotation: 'Sanchez',
          },
          {
            id: 'che-acheampong',
            team: 'home',
            jerseyNumber: 34,
            x: 22.0,
            y: 78.0,
            annotation: 'Acheampong',
          },
          {
            id: 'che-lacroix',
            team: 'home',
            jerseyNumber: 4,
            x: 18.0,
            y: 50.0,
            annotation: 'Lacroix',
          },
          {
            id: 'che-colwill',
            team: 'home',
            jerseyNumber: 6,
            x: 22.0,
            y: 22.0,
            annotation: 'Colwill',
          },
          {
            id: 'che-james',
            team: 'home',
            jerseyNumber: 24,
            x: 38.0,
            y: 62.0,
            annotation: 'James',
          },
          {
            id: 'che-enzo',
            team: 'home',
            jerseyNumber: 8,
            x: 36.0,
            y: 38.0,
            annotation: 'Enzo',
          },
          {
            id: 'che-gusto',
            team: 'home',
            jerseyNumber: 27,
            x: 58.0,
            y: 88.0,
            annotation: 'Gusto',
          },
          {
            id: 'che-palmer',
            team: 'home',
            jerseyNumber: 20,
            x: 56.0,
            y: 64.0,
            annotation: 'Palmer',
          },
          {
            id: 'che-rogers',
            team: 'home',
            jerseyNumber: 19,
            x: 58.0,
            y: 36.0,
            annotation: 'Rogers',
          },
          {
            id: 'che-hato',
            team: 'home',
            jerseyNumber: 33,
            x: 58.0,
            y: 12.0,
            annotation: 'Hato',
          },
          {
            id: 'che-pedro',
            team: 'home',
            jerseyNumber: 9,
            x: 72.0,
            y: 50.0,
            annotation: 'J.Pedro',
          },
          {
            id: 'ful-leno',
            team: 'away',
            jerseyNumber: 1,
            x: 94.0,
            y: 50.0,
            annotation: 'Leno',
          },
          {
            id: 'ful-castagne',
            team: 'away',
            jerseyNumber: 21,
            x: 76.0,
            y: 15.0,
            annotation: 'Castagne',
          },
          {
            id: 'ful-cuenca',
            team: 'away',
            jerseyNumber: 15,
            x: 78.0,
            y: 38.0,
            annotation: 'Cuenca',
          },
          {
            id: 'ful-bassey',
            team: 'away',
            jerseyNumber: 3,
            x: 78.0,
            y: 62.0,
            annotation: 'Bassey',
          },
          {
            id: 'ful-robinson',
            team: 'away',
            jerseyNumber: 33,
            x: 76.0,
            y: 85.0,
            annotation: 'Robinson',
          },
          {
            id: 'ful-bobb',
            team: 'away',
            jerseyNumber: 11,
            x: 52.0,
            y: 18.0,
            annotation: 'Bobb',
          },
          {
            id: 'ful-berge',
            team: 'away',
            jerseyNumber: 16,
            x: 54.0,
            y: 40.0,
            annotation: 'Berge',
          },
          {
            id: 'ful-iwobi',
            team: 'away',
            jerseyNumber: 17,
            x: 54.0,
            y: 60.0,
            annotation: 'Iwobi',
          },
          {
            id: 'ful-palacios',
            team: 'away',
            jerseyNumber: 20,
            x: 52.0,
            y: 82.0,
            annotation: 'Palacios',
          },
          {
            id: 'ful-king',
            team: 'away',
            jerseyNumber: 7,
            x: 32.0,
            y: 42.0,
            annotation: 'King',
          },
          {
            id: 'ful-garcia',
            team: 'away',
            jerseyNumber: 9,
            x: 34.0,
            y: 58.0,
            annotation: 'Garcia',
          },
        ],
        arrows: [],
        zones: [],
      },
    ],
  },
};
