import type { IPlayer } from '@/lib/types';

/**
 * Arsenal FC の選手データ
 * teamId: 42 (API-Football の Arsenal チームID)
 */
export const ARSENAL_PLAYERS: IPlayer[] = [
  {
    id: 2273,
    teamId: 42,
    name: 'Kepa',
    number: 13,
    position: 'Goalkeeper',
  },
  {
    id: 19465,
    teamId: 42,
    name: 'David Raya',
    number: 1,
    position: 'Goalkeeper',
  },
  {
    id: 337933,
    teamId: 42,
    name: 'Alexei Rojas Fedorushchenko',
    number: 51,
    position: 'Goalkeeper',
  },
  {
    id: 342243,
    teamId: 42,
    name: 'T. Setford',
    number: 35,
    position: 'Goalkeeper',
  },
  {
    id: 157052,
    teamId: 42,
    name: 'R. Calafiori',
    number: 33,
    position: 'Defender',
  },
  {
    id: 22224,
    teamId: 42,
    name: 'Gabriel Magalhães',
    number: 6,
    position: 'Defender',
  },
  {
    id: 127817,
    teamId: 42,
    name: 'P. Hincapié',
    number: 5,
    position: 'Defender',
  },
  {
    id: 313245,
    teamId: 42,
    name: 'M. Lewis-Skelly',
    number: 49,
    position: 'Defender',
  },
  {
    id: 333682,
    teamId: 42,
    name: 'Cristhian Mosquera',
    number: 3,
    position: 'Defender',
  },
  {
    id: 380696,
    teamId: 42,
    name: 'Joshua Nichols',
    number: 2,
    position: 'Defender',
  },
  {
    id: 22090,
    teamId: 42,
    name: 'W. Saliba',
    number: 2,
    position: 'Defender',
  },
  {
    id: 482903,
    teamId: 42,
    name: 'M. Salmon',
    number: 89,
    position: 'Defender',
  },
  {
    id: 38746,
    teamId: 42,
    name: 'J. Timber',
    number: 12,
    position: 'Defender',
  },
  {
    id: 19959,
    teamId: 42,
    name: 'B. White',
    number: 4,
    position: 'Defender',
  },
  {
    id: 442044,
    teamId: 42,
    name: 'M. Dowman',
    number: 56,
    position: 'Midfielder',
  },
  {
    id: 19586,
    teamId: 42,
    name: 'E. Eze',
    number: 10,
    position: 'Midfielder',
  },
  {
    id: 47311,
    teamId: 42,
    name: 'Mikel Merino',
    number: 23,
    position: 'Attacker',
  },
  {
    id: 30407,
    teamId: 42,
    name: 'C. Nørgaard',
    number: 16,
    position: 'Midfielder',
  },
  {
    id: 313236,
    teamId: 42,
    name: 'E. Nwaneri',
    number: 22,
    position: 'Midfielder',
  },
  {
    id: 37127,
    teamId: 42,
    name: 'M. Ødegaard',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 2937,
    teamId: 42,
    name: 'D. Rice',
    number: 41,
    position: 'Midfielder',
  },
  {
    id: 47315,
    teamId: 42,
    name: 'Martín Zubimendi',
    number: 36,
    position: 'Midfielder',
  },
  {
    id: 18979,
    teamId: 42,
    name: 'V. Gyökeres',
    number: 14,
    position: 'Attacker',
  },
  {
    id: 457731,
    teamId: 42,
    name: 'A. Annous',
    number: 71,
    position: 'Attacker',
  },
  {
    id: 978,
    teamId: 42,
    name: 'K. Havertz',
    number: 29,
    position: 'Attacker',
  },
  {
    id: 136723,
    teamId: 42,
    name: 'N. Madueke',
    number: 20,
    position: 'Attacker',
  },
  {
    id: 127769,
    teamId: 42,
    name: 'Gabriel Martinelli',
    number: 11,
    position: 'Attacker',
  },
  {
    id: 284571,
    teamId: 42,
    name: 'C. Sagoe',
    number: 11,
    position: 'Attacker',
  },
  {
    id: 1460,
    teamId: 42,
    name: 'B. Saka',
    number: 7,
    position: 'Midfielder',
  },
  {
    id: 1946,
    teamId: 42,
    name: 'L. Trossard',
    number: 19,
    position: 'Midfielder',
  },
];
