import type { IPlayer } from '@/lib/types';

/**
 * Chelsea FC の選手データ
 * teamId: 49 (API-Football の Chelsea チームID)
 */
export const CHELSEA_PLAYERS: IPlayer[] = [
  {
    id: 298061,
    teamId: 49,
    name: 'Ted Curd',
    number: 13,
    position: 'Goalkeeper',
  },
  {
    id: 286616,
    teamId: 49,
    name: 'F. Jörgensen',
    number: 12,
    position: 'Goalkeeper',
  },
  {
    id: 287868,
    teamId: 49,
    name: 'Max Merrick',
    number: 50,
    position: 'Goalkeeper',
  },
  {
    id: 18959,
    teamId: 49,
    name: 'Robert Sánchez',
    number: 1,
    position: 'Goalkeeper',
  },
  {
    id: 64167,
    teamId: 49,
    name: 'G. Słonina',
    number: 44,
    position: 'Goalkeeper',
  },
  {
    id: 366735,
    teamId: 49,
    name: 'Joshua Kofi Acheampong',
    number: 34,
    position: 'Defender',
  },
  {
    id: 19145,
    teamId: 49,
    name: 'T. Adarabioyo',
    number: 4,
    position: 'Defender',
  },
  {
    id: 95,
    teamId: 49,
    name: 'B. Badiashile',
    number: 5,
    position: 'Defender',
  },
  {
    id: 19720,
    teamId: 49,
    name: 'T. Chalobah',
    number: 23,
    position: 'Defender',
  },
  {
    id: 152953,
    teamId: 49,
    name: 'L. Colwill',
    number: 6,
    position: 'Defender',
  },
  {
    id: 47380,
    teamId: 49,
    name: 'Marc Cucurella',
    number: 3,
    position: 'Defender',
  },
  {
    id: 22094,
    teamId: 49,
    name: 'W. Fofana',
    number: 29,
    position: 'Defender',
  },
  {
    id: 161907,
    teamId: 49,
    name: 'M. Gusto',
    number: 27,
    position: 'Defender',
  },
  {
    id: 341642,
    teamId: 49,
    name: 'J. Hato',
    number: 21,
    position: 'Defender',
  },
  {
    id: 19545,
    teamId: 49,
    name: 'R. James',
    number: 24,
    position: 'Midfielder',
  },
  {
    id: 305834,
    teamId: 49,
    name: 'Andrey Santos',
    number: 17,
    position: 'Midfielder',
  },
  {
    id: 398000,
    teamId: 49,
    name: 'G. Antwi',
    number: 2,
    position: 'Midfielder',
  },
  {
    id: 311334,
    teamId: 49,
    name: 'F. Buonanotte',
    number: 40,
    position: 'Midfielder',
  },
  {
    id: 116117,
    teamId: 49,
    name: 'M. Caicedo',
    number: 25,
    position: 'Midfielder',
  },
  {
    id: 308678,
    teamId: 49,
    name: 'Dário Essugo',
    number: 14,
    position: 'Midfielder',
  },
  {
    id: 5996,
    teamId: 49,
    name: 'E. Fernández',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 394167,
    teamId: 49,
    name: 'O. Harrison',
    number: 6,
    position: 'Midfielder',
  },
  {
    id: 282125,
    teamId: 49,
    name: 'R. Lavia',
    number: 45,
    position: 'Midfielder',
  },
  {
    id: 152982,
    teamId: 49,
    name: 'C. Palmer',
    number: 10,
    position: 'Midfielder',
  },
  {
    id: 327733,
    teamId: 49,
    name: 'Sam Rak-Sakyi',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 482888,
    teamId: 49,
    name: 'R. Walsh',
    number: 46,
    position: 'Midfielder',
  },
  {
    id: 161948,
    teamId: 49,
    name: 'L. Delap',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 425733,
    teamId: 49,
    name: 'Estêvão',
    number: 41,
    position: 'Attacker',
  },
  {
    id: 284324,
    teamId: 49,
    name: 'A. Garnacho',
    number: 49,
    position: 'Midfielder',
  },
  {
    id: 334037,
    teamId: 49,
    name: 'Tyrique George',
    number: 32,
    position: 'Attacker',
  },
  {
    id: 286894,
    teamId: 49,
    name: 'J. Bynoe-Gittens',
    number: 11,
    position: 'Attacker',
  },
  {
    id: 392270,
    teamId: 49,
    name: 'Marc Guiu',
    number: 38,
    position: 'Attacker',
  },
  {
    id: 10329,
    teamId: 49,
    name: 'João Pedro',
    number: 20,
    position: 'Attacker',
  },
  {
    id: 359117,
    teamId: 49,
    name: 'Shumaira Mheuka',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 1864,
    teamId: 49,
    name: 'Pedro Neto',
    number: 7,
    position: 'Midfielder',
  },
];
