import type { IPlayer } from '@/lib/types';

/**
 * Liverpool FC の選手データ
 * teamId: 40 (API-Football の Liverpool チームID)
 */
export const LIVERPOOL_PLAYERS: IPlayer[] = [
  {
    id: 280,
    teamId: 40,
    name: 'Alisson Becker',
    number: 1,
    position: 'Goalkeeper',
  },
  {
    id: 24760,
    teamId: 40,
    name: 'G. Mamardashvili',
    number: 25,
    position: 'Goalkeeper',
  },
  {
    id: 415992,
    teamId: 40,
    name: 'K. Miściur',
    number: 74,
    position: 'Goalkeeper',
  },
  {
    id: 342467,
    teamId: 40,
    name: 'Á. Pécsi',
    number: 41,
    position: 'Goalkeeper',
  },
  {
    id: 18889,
    teamId: 40,
    name: 'F. Woodman',
    number: 28,
    position: 'Goalkeeper',
  },
  {
    id: 180317,
    teamId: 40,
    name: 'C. Bradley',
    number: 12,
    position: 'Defender',
  },
  {
    id: 287106,
    teamId: 40,
    name: 'Josh Davidson',
    number: 16,
    position: 'Defender',
  },
  {
    id: 284,
    teamId: 40,
    name: 'J. Gomez',
    number: 2,
    position: 'Defender',
  },
  {
    id: 206254,
    teamId: 40,
    name: 'M. Kerkez',
    number: 6,
    position: 'Defender',
  },
  {
    id: 1145,
    teamId: 40,
    name: 'I. Konaté',
    number: 5,
    position: 'Defender',
  },
  {
    id: 409047,
    teamId: 40,
    name: 'G. Leoni',
    number: 15,
    position: 'Defender',
  },
  {
    id: 328081,
    teamId: 40,
    name: 'W. Omoruyi',
    number: 3,
    position: 'Defender',
  },
  {
    id: 380666,
    teamId: 40,
    name: 'C. Pinnington',
    number: 15,
    position: 'Defender',
  },
  {
    id: 135525,
    teamId: 40,
    name: 'C. Ramsay',
    number: 2,
    position: 'Defender',
  },
  {
    id: 289,
    teamId: 40,
    name: 'A. Robertson',
    number: 26,
    position: 'Defender',
  },
  {
    id: 162904,
    teamId: 40,
    name: 'R. Williams',
    number: 46,
    position: 'Defender',
  },
  {
    id: 290,
    teamId: 40,
    name: 'V. van Dijk',
    number: 4,
    position: 'Defender',
  },
  {
    id: 8500,
    teamId: 40,
    name: 'W. Endo',
    number: 3,
    position: 'Midfielder',
  },
  {
    id: 152654,
    teamId: 40,
    name: 'J. Frimpong',
    number: 30,
    position: 'Midfielder',
  },
  {
    id: 542,
    teamId: 40,
    name: 'R. Gravenberch',
    number: 38,
    position: 'Midfielder',
  },
  {
    id: 293,
    teamId: 40,
    name: 'C. Jones',
    number: 17,
    position: 'Midfielder',
  },
  {
    id: 339205,
    teamId: 40,
    name: 'M. Laffey',
    number: 6,
    position: 'Midfielder',
  },
  {
    id: 6716,
    teamId: 40,
    name: 'A. Mac Allister',
    number: 10,
    position: 'Midfielder',
  },
  {
    id: 389032,
    teamId: 40,
    name: 'K. Morrison',
    number: 7,
    position: 'Midfielder',
  },
  {
    id: 407032,
    teamId: 40,
    name: 'A. Nallo',
    number: 4,
    position: 'Midfielder',
  },
  {
    id: 397997,
    teamId: 40,
    name: 'T. Nyoni',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 301286,
    teamId: 40,
    name: 'Tommy Pilling',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 1096,
    teamId: 40,
    name: 'D. Szoboszlai',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 203224,
    teamId: 40,
    name: 'F. Wirtz',
    number: 7,
    position: 'Midfielder',
  },
  {
    id: 30410,
    teamId: 40,
    name: 'F. Chiesa',
    number: 14,
    position: 'Attacker',
  },
  {
    id: 314661,
    teamId: 40,
    name: 'J. Danns',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 340246,
    teamId: 40,
    name: 'Trent Toure Kone Doherty',
    number: 11,
    position: 'Attacker',
  },
  {
    id: 174565,
    teamId: 40,
    name: 'H. Ekitike',
    number: 22,
    position: 'Attacker',
  },
  {
    id: 344223,
    teamId: 40,
    name: 'K. Figueroa',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 247,
    teamId: 40,
    name: 'C. Gakpo',
    number: 18,
    position: 'Attacker',
  },
  {
    id: 286764,
    teamId: 40,
    name: 'Kaide Gordon',
    number: 10,
    position: 'Attacker',
  },
  {
    id: 2864,
    teamId: 40,
    name: 'A. Isak',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 452685,
    teamId: 40,
    name: 'R. Ngumoha',
    number: 73,
    position: 'Attacker',
  },
  {
    id: 306,
    teamId: 40,
    name: 'Mohamed Salah',
    number: 11,
    position: 'Midfielder',
  },
];
