import type { IPlayer } from '@/lib/types';

/**
 * Manchester City の選手データ
 * teamId: 50 (API-Football の Manchester City チームID)
 */
export const MANCHESTER_CITY_PLAYERS: IPlayer[] = [
  {
    id: 19012,
    teamId: 50,
    name: 'M. Bettinelli',
    number: 13,
    position: 'Goalkeeper',
  },
  {
    id: 1622,
    teamId: 50,
    name: 'G. Donnarumma',
    number: 25,
    position: 'Goalkeeper',
  },
  {
    id: 25004,
    teamId: 50,
    name: 'S. Ortega',
    number: 18,
    position: 'Goalkeeper',
  },
  {
    id: 162489,
    teamId: 50,
    name: 'J. Trafford',
    number: 1,
    position: 'Goalkeeper',
  },
  {
    id: 21138,
    teamId: 50,
    name: 'R. Aït-Nouri',
    number: 21,
    position: 'Defender',
  },
  {
    id: 18861,
    teamId: 50,
    name: 'N. Aké',
    number: 6,
    position: 'Defender',
  },
  {
    id: 451583,
    teamId: 50,
    name: 'K. Braithwaite',
    number: 61,
    position: 'Defender',
  },
  {
    id: 567,
    teamId: 50,
    name: 'Rúben Dias',
    number: 3,
    position: 'Defender',
  },
  {
    id: 129033,
    teamId: 50,
    name: 'J. Gvardiol',
    number: 24,
    position: 'Defender',
  },
  {
    id: 360114,
    teamId: 50,
    name: 'A. Khusanov',
    number: 45,
    position: 'Defender',
  },
  {
    id: 284230,
    teamId: 50,
    name: 'R. Lewis',
    number: 82,
    position: 'Defender',
  },
  {
    id: 382358,
    teamId: 50,
    name: 'S. Mfuni',
    number: 5,
    position: 'Defender',
  },
  {
    id: 626,
    teamId: 50,
    name: 'J. Stones',
    number: 5,
    position: 'Defender',
  },
  {
    id: 278133,
    teamId: 50,
    name: 'Oscar Bobb',
    number: 52,
    position: 'Midfielder',
  },
  {
    id: 156477,
    teamId: 50,
    name: 'R. Cherki',
    number: 10,
    position: 'Attacker',
  },
  {
    id: 631,
    teamId: 50,
    name: 'P. Foden',
    number: 47,
    position: 'Midfielder',
  },
  {
    id: 347305,
    teamId: 50,
    name: 'Jaden Heskey',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 2291,
    teamId: 50,
    name: 'M. Kovačić',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 442048,
    teamId: 50,
    name: 'R. McAidoo',
    number: 56,
    position: 'Midfielder',
  },
  {
    id: 161933,
    teamId: 50,
    name: 'Nico González',
    number: 14,
    position: 'Midfielder',
  },
  {
    id: 41621,
    teamId: 50,
    name: 'Matheus Nunes',
    number: 27,
    position: 'Defender',
  },
  {
    id: 307123,
    teamId: 50,
    name: "N. O'Reilly",
    number: 33,
    position: 'Defender',
  },
  {
    id: 19130,
    teamId: 50,
    name: 'K. Phillips',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 36902,
    teamId: 50,
    name: 'T. Reijnders',
    number: 4,
    position: 'Midfielder',
  },
  {
    id: 44,
    teamId: 50,
    name: 'Rodri',
    number: 16,
    position: 'Midfielder',
  },
  {
    id: 636,
    teamId: 50,
    name: 'Bernardo Silva',
    number: 20,
    position: 'Midfielder',
  },
  {
    id: 1422,
    teamId: 50,
    name: 'J. Doku',
    number: 11,
    position: 'Attacker',
  },
  {
    id: 1100,
    teamId: 50,
    name: 'E. Haaland',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 448969,
    teamId: 50,
    name: 'Reigan Heskey',
    number: 92,
    position: 'Attacker',
  },
  {
    id: 81573,
    teamId: 50,
    name: 'Omar Marmoush',
    number: 7,
    position: 'Attacker',
  },
  {
    id: 380681,
    teamId: 50,
    name: 'D. Mukasa',
    number: 10,
    position: 'Attacker',
  },
  {
    id: 266657,
    teamId: 50,
    name: 'Sávio',
    number: 26,
    position: 'Attacker',
  },
];
