import type { IPlayer } from '@/lib/types';

/**
 * Tottenham Hotspur の選手データ
 * teamId: 47 (API-Football の Tottenham チームID)
 */
export const TOTTENHAM_PLAYERS: IPlayer[] = [
  {
    id: 156428,
    teamId: 47,
    name: 'B. Austin',
    number: 40,
    position: 'Goalkeeper',
  },
  {
    id: 344247,
    teamId: 47,
    name: 'Luca Gunter',
    number: 46,
    position: 'Goalkeeper',
  },
  {
    id: 265826,
    teamId: 47,
    name: 'A. Kinský',
    number: 31,
    position: 'Goalkeeper',
  },
  {
    id: 31354,
    teamId: 47,
    name: 'G. Vicario',
    number: 1,
    position: 'Goalkeeper',
  },
  {
    id: 467839,
    teamId: 47,
    name: 'J. Byfield',
    number: 67,
    position: 'Defender',
  },
  {
    id: 25287,
    teamId: 47,
    name: 'K. Danso',
    number: 4,
    position: 'Defender',
  },
  {
    id: 164,
    teamId: 47,
    name: 'B. Davies',
    number: 33,
    position: 'Defender',
  },
  {
    id: 328089,
    teamId: 47,
    name: 'A. Gray',
    number: 14,
    position: 'Defender',
  },
  {
    id: 459203,
    teamId: 47,
    name: 'M. Hardy',
    number: 66,
    position: 'Defender',
  },
  {
    id: 47519,
    teamId: 47,
    name: 'Pedro Porro',
    number: 23,
    position: 'Defender',
  },
  {
    id: 30776,
    teamId: 47,
    name: 'C. Romero',
    number: 17,
    position: 'Defender',
  },
  {
    id: 557539,
    teamId: 47,
    name: 'J. Rowswell',
    number: 76,
    position: 'Defender',
  },
  {
    id: 19235,
    teamId: 47,
    name: 'D. Spence',
    number: 24,
    position: 'Defender',
  },
  {
    id: 204039,
    teamId: 47,
    name: 'D. Udogie',
    number: 13,
    position: 'Defender',
  },
  {
    id: 152849,
    teamId: 47,
    name: 'M. van de Ven',
    number: 37,
    position: 'Defender',
  },
  {
    id: 863,
    teamId: 47,
    name: 'R. Bentancur',
    number: 30,
    position: 'Midfielder',
  },
  {
    id: 347316,
    teamId: 47,
    name: 'L. Bergvall',
    number: 15,
    position: 'Midfielder',
  },
  {
    id: 18968,
    teamId: 47,
    name: 'Y. Bissouma',
    number: 8,
    position: 'Midfielder',
  },
  {
    id: 284417,
    teamId: 47,
    name: 'Dante Jamel Cassanova',
    number: 4,
    position: 'Midfielder',
  },
  {
    id: 349383,
    teamId: 47,
    name: 'O. Irow',
    number: 11,
    position: 'Midfielder',
  },
  {
    id: 15911,
    teamId: 47,
    name: 'M. Kudus',
    number: 20,
    position: 'Midfielder',
  },
  {
    id: 310531,
    teamId: 47,
    name: 'Rio Kyerematen',
    number: 2,
    position: 'Midfielder',
  },
  {
    id: 18784,
    teamId: 47,
    name: 'J. Maddison',
    number: 10,
    position: 'Midfielder',
  },
  {
    id: 380689,
    teamId: 47,
    name: 'C. Olusesi',
    number: 6,
    position: 'Midfielder',
  },
  {
    id: 41104,
    teamId: 47,
    name: 'João Palhinha',
    number: 6,
    position: 'Midfielder',
  },
  {
    id: 237129,
    teamId: 47,
    name: 'P. Sarr',
    number: 29,
    position: 'Midfielder',
  },
  {
    id: 162016,
    teamId: 47,
    name: 'X. Simons',
    number: 7,
    position: 'Midfielder',
  },
  {
    id: 380688,
    teamId: 47,
    name: 'Y. Akhamrich',
    number: 70,
    position: 'Attacker',
  },
  {
    id: 129711,
    teamId: 47,
    name: 'B. Johnson',
    number: 22,
    position: 'Midfielder',
  },
  {
    id: 21104,
    teamId: 47,
    name: 'R. Kolo Muani',
    number: 39,
    position: 'Attacker',
  },
  {
    id: 30435,
    teamId: 47,
    name: 'D. Kulusevski',
    number: 21,
    position: 'Attacker',
  },
  {
    id: 557490,
    teamId: 47,
    name: 'E. Lehane',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 336564,
    teamId: 47,
    name: 'W. Odobert',
    number: 28,
    position: 'Midfielder',
  },
  {
    id: 2413,
    teamId: 47,
    name: 'Richarlison',
    number: 9,
    position: 'Attacker',
  },
  {
    id: 162552,
    teamId: 47,
    name: 'D. Scarlett',
    number: 44,
    position: 'Attacker',
  },
  {
    id: 18883,
    teamId: 47,
    name: 'D. Solanke',
    number: 19,
    position: 'Attacker',
  },
  {
    id: 270510,
    teamId: 47,
    name: 'M. Tel',
    number: 11,
    position: 'Attacker',
  },
  {
    id: 557391,
    teamId: 47,
    name: 'T. Thompson',
    number: 14,
    position: 'Attacker',
  },
  {
    id: 465310,
    teamId: 47,
    name: 'L. Williams-Barnett',
    number: 10,
    position: 'Attacker',
  },
];
